trainer:
  init:
    model:
      name: gnn
      architecture:
        type: graphsage
        n_feat: 128
        n_class: 40
        hidden_dim: 1024
        num_layers: 3
        dropout: 0.5
        aggregator: mean
      task:
        to_float16: true
        disable_log_softmax: false
        compute_eval_metrics: false
    backend:
      backend_type: CSX
      cluster_config:
        python_paths:
        - $REPO_ROOT/src/cerebras/modelzoo/../..
    model_dir: $REPO_ROOT/src/cerebras/modelzoo/../../../model_dirs/ogbn_arxiv_graphsage_pyg_throughput_cache
    optimizer:
      AdamW:
        params: []
        lr: 0.003
        weight_decay: 0.0005
    precision:
      enabled: true
      fp16_type: float16
      loss_scaling_factor: dynamic
    loop:
      max_steps: 500
      steps_per_epoch: 20
      eval_frequency: null
    logging:
      log_steps: 20
    callbacks:
    - CheckLoss: {}
    - LogOptimizerParamGroup:
        keys: lr
    - ComputeNorm: {}
    - ModelEvalMetrics: {}
    - RateProfiler: {}
    - DurationProfiler: {}
    - FlopUtilization: {}
    - SavePerformanceData: {}
    - DumpAvailableTensorNames: {}
    - ModelZooParamsMetadata: {}
    - SamplesStreamedInfo: {}
    loggers:
    - ProgressLogger: {}
    - TensorBoardLogger: {}
    - TelemetryLogger: {}
    seed: 42
  fit:
    train_dataloader:
      data_processor: GNNDataProcessor
      dataset_name: ogbn-arxiv
      dataset: ogbn_arxiv
      dataset_profiles:
        ogbn_arxiv:
          dataset_name: ogbn-arxiv
          data_dir: $MODELZOO_ROOT/models/gnn/data/datasets
          pad_node_id: 0
      data_dir: $REPO_ROOT/src/cerebras/modelzoo/models/gnn/data/datasets
      sampling_mode: neighbor
      fanouts:
      - 15
      - 10
      - 5
      cache_fraction: 1.0
      sampler_seed: 42
      batch_size: 4096
      drop_last: false
      num_workers: 40
      shuffle: true
      prefetch_factor: 2
      persistent_workers: true
      pin_memory: true
      split: train
      pad_node_id: 0
    val_dataloader:
    - data_processor: GNNDataProcessor
      dataset_name: ogbn-arxiv
      dataset: ogbn_arxiv
      dataset_profiles:
        ogbn_arxiv:
          dataset_name: ogbn-arxiv
          data_dir: $MODELZOO_ROOT/models/gnn/data/datasets
          pad_node_id: 0
      data_dir: $REPO_ROOT/src/cerebras/modelzoo/models/gnn/data/datasets
      sampling_mode: neighbor
      fanouts:
      - 15
      - 10
      - 5
      sampler_seed: 42
      batch_size: 4096
      drop_last: false
      num_workers: 40
      shuffle: false
      prefetch_factor: 2
      persistent_workers: true
      pin_memory: true
      split: valid
      pad_node_id: 0
  validate:
    val_dataloader:
      data_processor: GNNDataProcessor
      dataset_name: ogbn-arxiv
      dataset: ogbn_arxiv
      dataset_profiles:
        ogbn_arxiv:
          dataset_name: ogbn-arxiv
          data_dir: $MODELZOO_ROOT/models/gnn/data/datasets
          pad_node_id: 0
      data_dir: $REPO_ROOT/src/cerebras/modelzoo/models/gnn/data/datasets
      sampling_mode: neighbor
      fanouts:
      - 15
      - 10
      - 5
      sampler_seed: 42
      batch_size: 4096
      drop_last: false
      num_workers: 40
      shuffle: false
      prefetch_factor: 2
      persistent_workers: true
      pin_memory: true
      split: valid
      pad_node_id: 0
  validate_all:
    val_dataloaders:
    - data_processor: GNNDataProcessor
      dataset_name: ogbn-arxiv
      dataset: ogbn_arxiv
      dataset_profiles:
        ogbn_arxiv:
          dataset_name: ogbn-arxiv
          data_dir: $MODELZOO_ROOT/models/gnn/data/datasets
          pad_node_id: 0
      data_dir: $REPO_ROOT/src/cerebras/modelzoo/models/gnn/data/datasets
      sampling_mode: neighbor
      fanouts:
      - 15
      - 10
      - 5
      sampler_seed: 42
      batch_size: 4096
      drop_last: false
      num_workers: 40
      shuffle: false
      prefetch_factor: 2
      persistent_workers: true
      pin_memory: true
      split: valid
      pad_node_id: 0
