extends:
  - params_graphsage_ogbn_arxiv.yaml
  - components/architectures/input_pipelines/neighbor.yaml
  - components/runtime/pyg_profile_accuracy.yaml
  - components/runtime/pyg_cache_disabled.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/../../../model_dirs/ogbn_arxiv_graphsage_pyg_accuracy_nocache"
