trainer:
  init:
    model_dir: ./model_dir_gnn/ogbn_papers100m_graphsage
    seed: 42
    model:
      name: graphsage

      # Dataset-specific dimensions for ogbn-papers100M
      n_feat: 128
      n_class: 172
      n_hid: 256

      to_float16: False
      compute_eval_metrics: True
      disable_log_softmax: False
      core_architecture: GraphSAGE
      graphsage_hidden_dim: 256
      graphsage_num_layers: 3
      graphsage_dropout: 0.4
      graphsage_aggregator: mean

    optimizer:
      AdamW:
        params: []
        learning_rate: 0.002
        weight_decay: 0.0005

    loop:
      max_steps: 3000
      steps_per_epoch: 1000
      eval_frequency: 1000

    logging:
      log_steps: 25

  fit:
    train_dataloader:
      data_processor: GNNDataProcessor
      dataset_profiles: &ogbn_papers100m_dataset
        ogbn_papers100m:
          dataset_name: ogbn-papers100M
          data_dir: ./data/datasets/
          sampling_mode: neighbor
          fanouts: [15, 10, 5]
          pad_node_id: 0
      dataset: ogbn_papers100m
      batch_size: 1024
      drop_last_batch: False
      shuffle: True
      num_workers: 0
      sampler_seed: 42
      split: train

    val_dataloader: &ogbn_papers100m_eval_loader
      data_processor: GNNDataProcessor
      dataset_profiles: *ogbn_papers100m_dataset
      dataset: ogbn_papers100m
      batch_size: 2048
      drop_last_batch: False
      shuffle: False
      num_workers: 0
      sampler_seed: 42
      split: val

  validate:
    val_dataloader: *ogbn_papers100m_eval_loader

  validate_all:
    val_dataloaders:
      - *ogbn_papers100m_eval_loader

runconfig:
  python_paths:
    - src
