extends:
  - components/runtime/default.yaml
  - components/architectures/graphsage.yaml
  - components/datasets/ogbn_products.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/models/gnn/docs/artifacts/runtime/model_dirs/ogbn_products_graphsage"

    optimizer:
      AdamW:
        learning_rate: 0.003

    loop:
      max_steps: 1000
      steps_per_epoch: 40
      eval_frequency: 40

    logging:
      log_steps: 40
