trainer:
  init:
    model_dir: ./model_dir_gnn
    seed: 42
    model:
      name: graphsage

      # Dataset-specific dimensions
      n_feat: 500
      n_class: 3
      n_hid: 64

      # Wrapper parameters
      to_float16: False
      compute_eval_metrics: True
      disable_log_softmax: False
      core_architecture: GraphSAGE
      graphsage_hidden_dim: 128
      graphsage_num_layers: 2
      graphsage_dropout: 0.5
      graphsage_aggregator: mean

    optimizer:
      AdamW:
        params: []
        learning_rate: 0.01
        weight_decay: 0.0005

    loop:
      max_steps: 200
      steps_per_epoch: 4
      eval_frequency: 4

    logging:
      log_steps: 1

  fit:
    train_dataloader:
      data_processor: GNNDataProcessor
      dataset_name: PubMed
      data_dir: ./data/datasets/
      sampling_mode: neighbor
      fanouts: [25, 10]
      batch_size: 16
      drop_last_batch: False
      shuffle: True
      num_workers: 0
      sampler_seed: 42
      split: train

    val_dataloader: &val_neighbor_params
      data_processor: GNNDataProcessor
      dataset_name: PubMed
      data_dir: ./data/datasets/
      sampling_mode: neighbor
      fanouts: [25, 10]
      batch_size: 64
      drop_last_batch: False
      shuffle: False
      num_workers: 0
      sampler_seed: 42
      split: val

  validate:
    val_dataloader: *val_neighbor_params

  validate_all:
    val_dataloaders:
      - *val_neighbor_params

runconfig:
  python_paths:
    - src
