extends:
  - params_gcn_ogbn_arxiv.yaml
  - components/runtime/amp.yaml
  - components/runtime/profile_throughput.yaml
  - components/runtime/cache_disabled.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/../../../model_dirs/ogbn_arxiv_gcn_throughput_nocache"
