trainer:
  init:
    model_dir: ./model_dir_gnn/ogbn_arxiv_graphsage
    seed: 42
    model:
      name: graphsage

      # Dataset-specific dimensions for ogbn-arxiv
      n_feat: 128
      n_class: 40
      n_hid: 256

      to_float16: False
      compute_eval_metrics: True
      disable_log_softmax: False
      core_architecture: GraphSAGE
      graphsage_hidden_dim: 256
      graphsage_num_layers: 2
      graphsage_dropout: 0.5
      graphsage_aggregator: mean

    optimizer:
      AdamW:
        learning_rate: 0.003
        weight_decay: 0.0005

    loop:
      max_steps: 2000
      steps_per_epoch: 89
      eval_frequency: 89

    logging:
      log_steps: 25

  fit:
    train_dataloader:
      data_processor: GNNDataProcessor
      dataset_profiles: &ogbn_arxiv_dataset
        ogbn_arxiv:
          dataset_name: ogbn-arxiv
          data_dir: ./data/datasets/
          sampling_mode: neighbor
          fanouts: [25, 15]
          pad_node_id: 0
      dataset: ogbn_arxiv
      batch_size: 1024
      drop_last_batch: False
      shuffle: True
      num_workers: 0
      sampler_seed: 42
      split: train

    val_dataloader: &ogbn_arxiv_eval_loader
      data_processor: GNNDataProcessor
      dataset_profiles: *ogbn_arxiv_dataset
      dataset: ogbn_arxiv
      batch_size: 2048
      drop_last_batch: False
      shuffle: False
      num_workers: 0
      sampler_seed: 42
      split: val

  validate:
    val_dataloader: *ogbn_arxiv_eval_loader

  validate_all:
    val_dataloaders:
      - *ogbn_arxiv_eval_loader

runconfig:
  python_paths:
    - src
