trainer:
  init:
    model_dir: ./model_dir_gnn/reddit_graphsage
    seed: 42
    model:
      name: graphsage

      # Dataset-specific dimensions
      n_feat: 602
      n_class: 41
      n_hid: 256

      # Wrapper parameters
      to_float16: False
      compute_eval_metrics: True
      disable_log_softmax: False
      core_architecture: GraphSAGE
      graphsage_hidden_dim: 256
      graphsage_num_layers: 2
      graphsage_dropout: 0.3
      graphsage_aggregator: mean

    optimizer:
      AdamW:
        params: []
        learning_rate: 0.003
        weight_decay: 0.0005

    loop:
      max_steps: 1500
      steps_per_epoch: 300
      eval_frequency: 300

    logging:
      log_steps: 10

  fit:
    train_dataloader:
      data_processor: GNNDataProcessor
      dataset_name: Reddit
      data_dir: ./data/datasets/
      sampling_mode: neighbor
      fanouts: [20, 10]
      batch_size: 512
      drop_last_batch: False
      shuffle: True
      num_workers: 0
      sampler_seed: 42
      split: train

    val_dataloader: &val_neighbor_params
      data_processor: GNNDataProcessor
      dataset_name: Reddit
      data_dir: ./data/datasets/
      sampling_mode: neighbor
      fanouts: [20, 10]
      batch_size: 1024
      drop_last_batch: False
      shuffle: False
      num_workers: 0
      sampler_seed: 42
      split: val

  validate:
    val_dataloader: *val_neighbor_params

  validate_all:
    val_dataloaders:
      - *val_neighbor_params

runconfig:
  python_paths:
    - src
