extends:
  - components/runtime/default.yaml
  - components/datasets/pubmed.yaml
  - components/architectures/gcn_sparse_matmul.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/models/gnn/docs/artifacts/runtime/model_dirs/PubMed_gcn_sparse_matmul"

    optimizer:
      AdamW:
        learning_rate: 0.01

    loop:
      max_steps: 1
      steps_per_epoch: 1
      eval_frequency: 10

    logging:
      log_steps: 1
