extends:
  - components/runtime/default.yaml
  - components/architectures/graphsage.yaml
  - components/datasets/mag240m.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/../../../model_dirs/mag240m_graphsage"

    optimizer:
      AdamW:
        learning_rate: 0.0015

    loop:
      max_steps: 3000
      steps_per_epoch: 120
      eval_frequency: 120

    logging:
      log_steps: 120
