extends:
  - components/runtime/default.yaml
  - components/architectures/graphsage.yaml
  - components/datasets/ogbn_arxiv.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/../../../model_dirs/ogbn_arxiv_graphsage_cached_static"

    optimizer:
      AdamW:
        learning_rate: 0.003

    loop:
      max_steps: 40
      steps_per_epoch: 20
      eval_frequency: null

    logging:
      log_steps: 1

  fit:
    train_dataloader:
      num_workers: 0
      static_batch_cache_size: 1

    val_dataloader:
      num_workers: 0
      cache_fraction: null
      static_batch_cache_size: 1

  validate:
    val_dataloader:
      num_workers: 0
      cache_fraction: null
      static_batch_cache_size: 1

  validate_all:
    val_dataloaders:
      - num_workers: 0
        cache_fraction: null
        static_batch_cache_size: 1
