extends:
  - components/runtime/default.yaml
  - components/architectures/graphsage.yaml
  - components/datasets/ogbn_arxiv.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/models/gnn/docs/artifacts/runtime/model_dirs/ogbn_arxiv_graphsage"

    optimizer:
      AdamW:
        learning_rate: 0.003

    loop:
      max_steps: 500
      steps_per_epoch: 20
      eval_frequency: 20

    logging:
      log_steps: 20
