extends:
  - components/runtime/default.yaml
  - components/architectures/graphsage.yaml
  - components/datasets/ogbn_papers100m.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/models/gnn/docs/artifacts/runtime/model_dirs/ogbn_papers100m_graphsage"

    optimizer:
      AdamW:
        learning_rate: 0.002

    loop:
      max_steps: 3000
      steps_per_epoch: 120
      eval_frequency: 120

    logging:
      log_steps: 120
