extends:
  - components/runtime/default.yaml
  - components/architectures/graph_transformer.yaml
  - components/datasets/pubmed.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/models/gnn/docs/artifacts/runtime/model_dirs/PubMed_graph_transformer"

    optimizer:
      AdamW:
        learning_rate: 0.01

    loop:
      max_steps: 200
      steps_per_epoch: 1
      eval_frequency: 10

    logging:
      log_steps: 1
