extends:
  - components/runtime/default.yaml
  - components/architectures/graphsage.yaml
  - components/datasets/ogbn_mag.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/../../../model_dirs/ogbn_mag_graphsage"

    optimizer:
      AdamW:
        learning_rate: 0.0025

    loop:
      max_steps: 2500
      steps_per_epoch: 100
      eval_frequency: 100

    logging:
      log_steps: 100
