extends:
  - components/runtime/default.yaml
  - components/architectures/graphsage.yaml
  - components/datasets/pubmed.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/models/gnn/docs/artifacts/runtime/model_dirs/PubMed_graphsage"

    optimizer:
      AdamW:
        learning_rate: 0.01

    loop:
      max_steps: 200
      steps_per_epoch: 8
      eval_frequency: 8

    logging:
      log_steps: 8

  fit:
    train_dataloader:
      batch_size: 8

    val_dataloader:
      batch_size: 64

  validate:
    val_dataloader:
      batch_size: 64

  validate_all:
    val_dataloaders:
      - batch_size: 64
