extends:
  - components/runtime/default.yaml
  - components/architectures/graphsage.yaml
  - components/datasets/reddit.yaml

trainer:
  init:
    model_dir: "$MODELZOO_ROOT/models/gnn/docs/artifacts/runtime/model_dirs/reddit_graphsage"

    optimizer:
      AdamW:
        learning_rate: 0.003

    loop:
      max_steps: 1500
      steps_per_epoch: 60
      eval_frequency: 60

    logging:
      log_steps: 60
